spring.application.name=catalogo

# Server
server.port=8080
server.forward-headers-strategy=framework

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/redflags_db
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.database-platform=MySQL8
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.root=INFO

# DevTools - Live Reload
spring.devtools.restart.enabled=true
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false